# Description: affine, MI, ASGD

#ImageTypes
FixedInternalImagePixelType = "float"
FixedImageDimension = 3
MovingInternalImagePixelType = "float"
MovingImageDimension = 3
UseDirectionCosines = true

#Components
Registration = "MultiResolutionRegistration"
FixedImagePyramid = "FixedSmoothingImagePyramid"
MovingImagePyramid = "MovingSmoothingImagePyramid"
Interpolator = "BSplineInterpolator"
Metric = "AdvancedMattesMutualInformation"
Optimizer = "AdaptiveStochasticGradientDescent"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"
Transform = "AffineTransform"

#(ErodeMask "false" )
ErodeFixedMask = true 
ErodeMovingMask = false 

NumberOfResolutions = 4
FinalGridSpacingInVoxels = [20.0, 20.0, 20.0]

HowToCombineTransforms = "Compose"
AutomaticTransformInitialization = true
AutomaticScalesEstimation = true

WriteTransformParametersEachIteration = false
WriteResultImage = false
CompressResultImage = true
ResultImageFormat = "nii"
WriteResultImageAfterEachResolution = false 
ShowExactMetricValue = false
ResultImagePixelType = "float"

#Maximum number of iterations in each resolution level:
MaximumNumberOfIterations = 500  

#Number of grey level bins in each resolution level:
NumberOfHistogramBins = 32 
FixedLimitRangeRatio = 0.0
MovingLimitRangeRatio = 0.0
FixedKernelBSplineOrder = 3
MovingKernelBSplineOrder = 3


#Number of spatial samples used to compute the mutual information in each resolution level:
ImageSampler = "RandomCoordinate"
FixedImageBSplineInterpolationOrder = 1 
UseRandomSampleRegion = false
NumberOfSpatialSamples = 2000 
NewSamplesEveryIteration = true
CheckNumberOfSamples = true
MaximumNumberOfSamplingAttempts = 10

#Order of B-Spline interpolation used in each resolution level:
BSplineInterpolationOrder = 1

#Order of B-Spline interpolation used for applying the final deformation:
FinalBSplineInterpolationOrder = 3

#Default pixel value for pixels that come from outside the picture:
DefaultPixelValue = 0

#SP: Param_a in each resolution level. a_k = a/(A+k+1)^alpha
#(SP_a 0.125 )

#SP: Param_A in each resolution level. a_k = a/(A+k+1)^alpha
SP_A = 20.0 

#SP: Param_alpha in each resolution level. a_k = a/(A+k+1)^alpha
SP_alpha = 1.0  


