FixedInternalImagePixelType = "float"
MovingInternalImagePixelType = "float"
AutomaticParameterEstimation = true
CheckNumberOfSamples = true
DefaultPixelValue = 0
FinalBSplineInterpolationOrder = 3
FixedImagePyramid = "FixedSmoothingImagePyramid"
ImageSampler = "RandomCoordinate"
Interpolator = "BSplineInterpolator"
MaximumNumberOfIterations = 256
MaximumNumberOfSamplingAttempts = 8
Metric = "AdvancedMattesMutualInformation"
MovingImagePyramid = "MovingSmoothingImagePyramid"
NewSamplesEveryIteration = true
NumberOfResolutions = 4
NumberOfSamplesForExactGradient = 4096
NumberOfSpatialSamples = 2048
Optimizer = "AdaptiveStochasticGradientDescent"
Registration = "MultiResolutionRegistration"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"
ResultImageFormat = "nii"
Transform = "EulerTransform"
WriteIterationInfo = false
WriteResultImage = true

