FixedImageDimension = 3
MovingImageDimension = 3

UseDirectionCosines = true

Registration = "MultiResolutionRegistration"
Interpolator = "BSplineInterpolator"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"

FixedImagePyramid = "FixedSmoothingImagePyramid"
MovingImagePyramid = "MovingSmoothingImagePyramid"

Optimizer = "AdaptiveStochasticGradientDescent"
Transform = "BSplineTransform"
Metric = "AdvancedMattesMutualInformation"

# ***************** Transformation **************************

FinalGridSpacingInPhysicalUnits = 16

GridSpacingSchedule = [4.0, 2.0, 1.0]

HowToCombineTransforms = "Compose"

# ******************* Similarity measure *********************

NumberOfHistogramBins = 32

ErodeMask = false

# ******************** Multiresolution **********************

NumberOfResolutions = 3

ImagePyramidSchedule = [4, 4, 4, 2, 2, 2, 1, 1, 1 ]

# ******************* Optimizer ****************************

MaximumNumberOfIterations = 500

# **************** Image sampling **********************

NumberOfSpatialSamples = 2048

NewSamplesEveryIteration = true
ImageSampler = "Random"

# ************* Interpolation and Resampling ****************

BSplineInterpolationOrder = 1

FinalBSplineInterpolationOrder = 3

DefaultPixelValue = 0

WriteResultImage = true
ResultImagePixelType = "short"
ResultImageFormat = "mhd"

