# **************** Image Types **************************
FixedInternalImagePixelType = "float"
MovingInternalImagePixelType = "float"
UseDirectionCosines = true

# **************** Main Components **************************
Registration = "MultiMetricMultiResolutionRegistration"
FixedImagePyramid = "FixedSmoothingImagePyramid"
MovingImagePyramid = "MovingSmoothingImagePyramid"
Interpolator = "BSplineInterpolator"
Metric = ["AdvancedNormalizedCorrelation", "MissingStructurePenalty", "PolydataDummyPenalty"]
Optimizer = "StandardGradientDescent"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"
Transform = "BSplineTransform"

# **************** Pyramid **************************
NumberOfResolutions = 3
ImagePyramidSchedule = [32, 32, 32, 16, 16, 16, 8, 8, 8 ]

# ***************** Transformation **************************
HowToCombineTransforms = "Compose"
FinalGridSpacingInPhysicalUnits = [12.0, 12.0, 12.0]

# ******************* Optimizer ****************************
MaximumNumberOfIterations = 200
SP_a = 50000 
# ******************* Metric ****************************
SubtractMean = true
Metric0Weight = 1 
Metric1Weight = 1e-7  
Metric2Weight = 0.0  
ErodeMask = false

# ******************* ImageSampler ****************************
ImageSampler = "RandomCoordinate"
NumberOfSpatialSamples = 1000 
CheckNumberOfSamples = true
MaximumNumberOfSamplingAttempts = 10
NewSamplesEveryIteration = true 

# ******************* Interpolator and Resampler *******************
FixedImageBSplineInterpolationOrder = [1, 1, 1]
MovingImageBSplineInterpolationOrder = [1, 1, 1]

# ******************* Output ****************************

#(WriteResultMeshAfterEachIteration "true" ) //for movie
WriteResultMeshAfterEachResolution = true
#(WriteTransformParametersAfterEachResolution "true")
#(WriteResultImageAfterEachResolution "true")

#(WriteResultImage "false")
WriteResultImage = true
DefaultPixelValue = 0
ResultImagePixelType = "float"
ResultImageFormat = "mhd"
