# ********** Image Types

FixedInternalImagePixelType = "float"
FixedImageDimension = 3
MovingInternalImagePixelType = "float"
MovingImageDimension = 3


# ********** Components

Registration = "MultiResolutionRegistration"
FixedImagePyramid = "FixedSmoothingImagePyramid"
MovingImagePyramid = "MovingSmoothingImagePyramid"
Interpolator = "BSplineInterpolator"
Metric = "AdvancedMattesMutualInformation"
Optimizer = "AdaptiveStochasticGradientDescent"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"
Transform = "BSplineTransform"


# ********** Pyramid

# Total number of resolutions
NumberOfResolutions = 3
ImagePyramidSchedule = [4, 4, 4, 2, 2, 2, 1, 1, 1]


# ********** Transform

#(FinalGridSpacingInPhysicalUnits 10.0 10.0 10.0)
FinalGridSpacingInPhysicalUnits = [5.0, 5.0, 5.0]
GridSpacingSchedule = [4.0, 2.0, 1.0]
HowToCombineTransforms = "Compose"


# ********** Optimizer

# Maximum number of iterations in each resolution level:
MaximumNumberOfIterations = 500
AutomaticParameterEstimation = true
UseAdaptiveStepSizes = true

ASGDParameterEstimationMethod = "OriginalButSigmoidToDefault"

MaximumStepLength = 0.5
SP_A = [10.000000, 10.000000, 10.000000]

# ********** Metric

NumberOfHistogramBins = 32
FixedKernelBSplineOrder = 1
MovingKernelBSplineOrder = 3
UseFastAndLowMemoryVersion = true


# ********** Several

WriteTransformParametersEachIteration = false
WriteTransformParametersEachResolution = true
WriteResultImageAfterEachResolution = false
WritePyramidImagesAfterEachResolution = false
WriteResultImage = false
ShowExactMetricValue = false
ErodeMask = false
UseDirectionCosines = true


# ********** ImageSampler

#Number of spatial samples used to compute the mutual information in each resolution level:
ImageSampler = "RandomCoordinate"
NumberOfSpatialSamples = 5000
NewSamplesEveryIteration = true
UseRandomSampleRegion = false


# ********** Interpolator and Resampler

#Order of B-Spline interpolation used in each resolution level:
BSplineInterpolationOrder = 1

#Order of B-Spline interpolation used for applying the final deformation:
FinalBSplineInterpolationOrder = 3

#Default pixel value for pixels that come from outside the picture:
DefaultPixelValue = 0


