# This file was created for affine transformation of the paper:
# "Deformable registration for longitudinal breast MRI screening
# Hatef Mehrabian, Yinlgli Lu, Lara Richmond, Anne L. Martel
# Journal of Digital Imaging, 2018
# DOI: 10.1007/s10278-018-0063-1

# parameter file for affine registration (Elaxtix version 4.7)
# C-style comments: //

# The internal pixel type, used for internal computations
# Leave to float in general. 
# NB: this is not the type of the input images! The pixel 
# type of the input images is automatically read from the 
# images themselves.
# This setting can be changed to "short" to save some memory
# in case of very large 3D images.
FixedInternalImagePixelType = "float"
MovingInternalImagePixelType = "float"

# The dimensions of the fixed and moving image
# Up to elastix 4.5 this had to be specified by the user.
# From elastix 4.6, this is not necessary anymore.
FixedImageDimension = 3
MovingImageDimension = 3

# Specify whether you want to take into account the so-called
# direction cosines of the images. Recommended: true.
# In some cases, the direction cosines of the image are corrupt,
# due to image format conversions for example. In that case, you 
# may want to set this option to "false".
UseDirectionCosines = true

# **************** Main Components **************************

# The following components should usually be left as they are:
Registration = "MultiMetricMultiResolutionRegistration"
Interpolator = "BSplineInterpolator"
ResampleInterpolator = "FinalBSplineInterpolator"
Resampler = "DefaultResampler"

# These may be changed to Fixed/MovingSmoothingImagePyramid.
# See the manual.
FixedImagePyramid = "FixedRecursiveImagePyramid"
MovingImagePyramid = "MovingRecursiveImagePyramid"

# The following components are most important:
# The optimizer AdaptiveStochasticGradientDescent (ASGD) works
# quite ok in general. The Transform and Metric are important
# and need to be chosen careful for each application. See manual.
Optimizer = "AdaptiveStochasticGradientDescent"
Transform = "BSplineTransform"
Metric = ["AdvancedMattesMutualInformation", "TransformRigidityPenalty"]
Metric0Weight = 1.0
Metric1Weight = 0.0

# ***************** Transformation **************************

# Whether transforms are combined by composition or by addition.
# In generally, Compose is the best option in most cases.
# It does not influence the results very much.
HowToCombineTransforms = "Compose"

# ******************* Similarity measure *********************

# Number of grey level bins in each resolution level,
# for the mutual information. 16 or 32 usually works fine.
# You could also employ a hierarchical strategy:
#(NumberOfHistogramBins 16 32 64)
NumberOfHistogramBins = 64

# If you use a mask, this option is important. 
# If the mask serves as region of interest, set it to false.
# If the mask indicates which pixels are valid, then set it to true.
# If you do not use a mask, the option doesn't matter.
ErodeMask = false

# ******************** Multiresolution **********************

# The number of resolutions. 1 Is only enough if the expected
# deformations are small. 3 or 4 mostly works fine. For large
# images and large deformations, 5 or 6 may even be useful.
NumberOfResolutions = 3

# ******************* Optimizer ****************************

# Maximum number of iterations in each resolution level:
# 200-500 works usually fine for affine registration.
# For more robustness, you may increase this to 1000-2000.
MaximumNumberOfIterations = 500

# **************** Image sampling **********************

# Number of spatial samples used to compute the mutual
# information (and its derivative) in each iteration.
# With an AdaptiveStochasticGradientDescent optimizer,
# in combination with the two options below, around 2000
# samples may already suffice.
NumberOfSpatialSamples = 4096

# Refresh these spatial samples in every iteration, and select
# them randomly. See the manual for information on other sampling
# strategies.
NewSamplesEveryIteration = true
ImageSampler = "Random"

# ************* Interpolation and Resampling ****************

FinalGridSpacingInPhysicalUnits = [8.0, 8.0, 8.0]

# Order of B-Spline interpolation used during registration/optimisation.
# It may improve accuracy if you set this to 3. Never use 0.
# An order of 1 gives linear interpolation. This is in most 
# applications a good choice.
BSplineInterpolationOrder = 3

# Order of B-Spline interpolation used for applying the final
# deformation.
# 3 gives good accuracy; recommended in most cases.
# 1 gives worse accuracy (linear interpolation)
# 0 gives worst accuracy, but is appropriate for binary images
# (masks, segmentations); equivalent to nearest neighbor interpolation.
FinalBSplineInterpolationOrder = 2

#Default pixel value for pixels that come from outside the picture:
DefaultPixelValue = 0

# Choose whether to generate the deformed moving image.
# You can save some time by setting this to false, if you are
# only interested in the final (nonrigidly) deformed moving image
# for example.
WriteResultImage = true

# The pixel type and format of the resulting deformed moving image
ResultImagePixelType = "float"

# **********************************************************************

